image: node:current-alpine

stages:
  - build
  - package

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules

# Build and test the Remix application
build:
  stage: build
  script:
    # Install dependencies
    - npm install
    # Build the application
    - npm run build
    # Run tests
    - npm run test
  artifacts:
    paths:
      - build/
      - public/
    expire_in: 1 week

# Package and push Docker image
package:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"
      --custom-platform=linux/arm/v7
  only:
    - tags
