image: node:current-alpine

stages:
  - build
  - package

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - api/node_modules
    - frontend/node_modules

# Build and test everything
build:
  stage: build
  script:
    # Install dependencies for both projects
    - cd api
    - npm install
    - cd ../frontend
    - npm install
    - cd ..
    # Build both projects
    - cd api
    - npm run build
    - cd ../frontend
    - npm run build
    - cd ..
    # Run tests for both projects
    - cd api
    - npm run test
    - cd ../frontend
    - npm run test
    - cd ..
  artifacts:
    paths:
      - api/dist
      - frontend/.next
    expire_in: 1 week

.build-image:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/${APP}"
      --dockerfile "${CI_PROJECT_DIR}/${APP}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/${APP}:${CI_COMMIT_REF_SLUG}"
      --custom-platform=linux/arm/v7
  only:
    - tags

package-api:
  extends: .build-image
  variables:
    APP: api

package-frontend:
  extends: .build-image
  variables:
    APP: frontend
